### ISSUE TITLE
fp32 onnx model을 session에 넣었을 때, error message

### ISSUE THREAD

**Issue by hanjoon** [furiosa-ai/furiosa-sdk#14]
Session에 fp32 onnx model을 넣을 경우, 현재 sdk에서는 에러를 출력합니다.
다만 에러 메시지가 다소 비직관적이어서 개선하면 좋을 것 같습니다.
현재 에러메시지는 다음과 같습니다.

~~~
root@hanjoon:~/furiosa-sdk/examples/furiosa-sdk-runtime# ./random_input_inference.py ../assets/fp32_models/MobileNetV2_10c_10d.onnx
INFO:furiosa_sdk_runtime._api.v1:successfully loaded dynamic library libnux.so.1.0.0
Loading and compiling the model ../assets/fp32_models/MobileNetV2_10c_10d.onnx
num_slices: 64
num_slices: 64
[1/6]  Compiling from onnx to dfg
thread '<unnamed>' panicked at 'no entry found for key', crates/npu-ir/src/furiosa_ir/furiosa_ir_onnx.rs:2647:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Any', crates/nux/src/session/mod.rs:108:10
Traceback (most recent call last):
  File "./random_input_inference.py", line 53, in <module>
    random_input_inference(model_path, num_inf=num_inf)
  File "./random_input_inference.py", line 16, in random_input_inference
    with session.create(str(model_path)) as sess:
  File "/usr/local/lib/python3.8/dist-packages/furiosa_sdk_runtime/session.py", line 248, in create
    return Session(model)
  File "/usr/local/lib/python3.8/dist-packages/furiosa_sdk_runtime/session.py", line 48, in __init__
    raise into_exception(err)
furiosa_sdk_runtime.errors.InternalError: unknown (native error code: 15)
~~~

**Comment by boncheolgu** [comment]
이 이슈는 컴파일러에서 처리해야할 것 같네요.

**Comment by hanjoon** [comment]
아 그렇군요 감사합니다~
그럼 이 이슈는 close하겠습니다.
