### ISSUE TITLE
UnboundLocalError: local variable 'libnux_path' referenced before assignment

### ISSUE THREAD

**Issue by ipkn-furiosa** [furiosa-ai/furiosa-sdk#18]
While running test program, the following exception is occured.

```
Traceback (most recent call last):
  File "random_input_inference.py", line 9, in <module>
    from furiosa_sdk_runtime.tensor import DataType
  File "/home/furiosa-demo/furiosa-sdk/venv/lib/python3.8/site-packages/furiosa_sdk_runtime/__init__.py", line 4, in <module>
    from furiosa_sdk_runtime import session, model, tensor, errors
  File "/home/furiosa-demo/furiosa-sdk/venv/lib/python3.8/site-packages/furiosa_sdk_runtime/session.py", line 9, in <module>
    from ._api import LIBNUX
  File "/home/furiosa-demo/furiosa-sdk/venv/lib/python3.8/site-packages/furiosa_sdk_runtime/_api/__init__.py", line 5, in <module>
    from .v1 import LIBNUX
  File "/home/furiosa-demo/furiosa-sdk/venv/lib/python3.8/site-packages/furiosa_sdk_runtime/_api/v1.py", line 77, in <module>
    LIBNUX = _find_native_libs()
  File "/home/furiosa-demo/furiosa-sdk/venv/lib/python3.8/site-packages/furiosa_sdk_runtime/_api/v1.py", line 57, in _find_native_libs
    libnux_path = _find_user_libs()
  File "/home/furiosa-demo/furiosa-sdk/venv/lib/python3.8/site-packages/furiosa_sdk_runtime/_api/v1.py", line 38, in _find_user_libs
    return libnux_path
UnboundLocalError: local variable 'libnux_path' referenced before assignment
```

**Comment by ipkn-furiosa** [comment]
Adding `libnux_path = None` here will solve the issue.

https://github.com/furiosa-ai/furiosa-sdk/blob/a0609bd6858651c84f7fc02ce6604fe4df2ec812/python/furiosa-sdk-runtime/furiosa_sdk_runtime/_api/v1.py#L27

**Comment by hyunsik** [comment]
Thank you for reporting the bug.
