### ISSUE TITLE
Unhashable type when CompletionQueue::recv fails

### ISSUE THREAD

**Issue by hyunsik** [furiosa-ai/furiosa-sdk#29]
See the error message. We need to handle the error case.
```
Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/furiosa-sdk-tests/furiosa-sdk/python/furiosa-sdk-runtime/tests/test_async_session.py", line 33, in test_run_async
    for key, _ in self.tester.queue:
  File "/home/jenkins/agent/workspace/furiosa-sdk-tests/furiosa-sdk/python/furiosa-sdk-runtime/furiosa_sdk_runtime/session.py", line 160, in __next__
    return self.recv()
  File "/home/jenkins/agent/workspace/furiosa-sdk-tests/furiosa-sdk/python/furiosa-sdk-runtime/furiosa_sdk_runtime/session.py", line 135, in recv
    raise into_exception(err)
  File "/home/jenkins/agent/workspace/furiosa-sdk-tests/furiosa-sdk/python/furiosa-sdk-runtime/furiosa_sdk_runtime/errors.py", line 159, in into_exception
    if err in _errors_to_exceptions.keys():
TypeError: unhashable type
```

**Comment by hyunsik** [comment]
it was fixed by #2a2595b.
